version: "3"

services:

  nginx:
    build: ./requirements/nginx
    image: nginx:mynginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - nginx-v:/var/www/html
    restart: always
 

volumes:
  nginx-v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aderose/data

