version: "3"

services:

#in container /var/log/service/log..access...

  nginx:
#    depends on:
#      - wordpress
    build: ./requirements/nginx
    image: nginx
    env_file:
      - ./.env
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - nginx-v:/var/www/html
    restart: always
    networks:
      - webapp

#  mariadb:
#    build: ./requirements/mariadb
#    restart: always
#    image: mariadb
#    env_file:
#      - ./.env
#    container_name: mariadb
#    ports:
#      - 3306:3306
#    volumes:
#      - DB:/var/lib/mysql
#    networks:
#      - webapp

#  wordpress:
#    depends on:
#      - mariadb
#    build: ./requirements/wordpress
#    image: wordpress
#    env_file:
#      - ./.env
#    container_name: wordpress
#    ports:
#      - 9000:9000
#    volumes:
#      - mariadb-v:/var/www/html
#    restart: always
#    networks:
#      - webapp


volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aderose/data/wp
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aderose/data/mariadb
  nginx-v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aderose/data/nginx-v

networks:
  webapp:
    driver: bridge
