version: "3"

volumes:
  wp-v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aderose/data/wp
  mariadb-v:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aderose/data/mariadb

services:

#in container /var/log/service/log..access...

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    env_file:
      - ./.env
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wp-v:/var/www/html:rw
    restart: always
    networks:
      - webapp

  mariadb:
    build: ./requirements/mariadb
    restart: always
    image: mariadb
    env_file:
      - ./.env
    container_name: mariadb
    volumes:
      - mariadb-v:/var/lib/mysql
    networks:
      - webapp

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - ./.env
    container_name: wordpress
    volumes:
      - wp-v:/var/www/html:rw
    restart: always
    networks:
      - webapp

networks:
  webapp:
    driver: bridge
