version: '3'

mariadb:
    container-name: dev_mariadb
    image: mariadb:focal
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD: 'pass'
    - MYSQL_DATABASE: 'dev_db'
    - MYSQL_USER: 'dev_user'
    - MYSQL_PASSWORD: 'pass'
    volumes: mariadb_data:/var/lib/mysql
    restart: always

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./requirements/mariadb/conf

