CREATE DATABASE $DB_NAME;
GRANT ALL ON *.* TO $ADMIN_USERNAME@$DB_HOST IDENTIFIED BY $ADMIN_PASSWORD WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE testtab
(
id INTEGER AUTO_INCREMENT,
name TEXT,
PRIMARY KEY (id)
) COMMENT='this is my test table';