-- CREATE DATABASE $DB_NAME;
GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'$DB_HOST' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE testtab
(
id INTEGER AUTO_INCREMENT,
name TEXT,
PRIMARY KEY (id)
) COMMENT='this is my test table';