CREATE DATABASE IF NOT EXISTS $DB_NAME;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$MYSQL_USER'@'$DB_HOST' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE TABLE testtab(id INTEGER AUTO_INCREMENT, name varchar(255), PRIMARY KEY (id));
-- CREATE TABLE testtab
-- (
-- id INTEGER AUTO_INCREMENT,
-- name TEXT,
-- PRIMARY KEY (id)
-- );